require("setup.remap")
require("setup.packer")
require("setup.set")
require("after.plugin.theme")
require("after.plugin.telescope")
require("after.plugin.treesitter")
require("after.plugin.lsp")
require("after.plugin.cmp")
require("after.plugin.theme")
require("after.plugin.matals")
require("after.plugin.harpoon")

