require("setup.remap")
require("setup.packer")
require("setup.set")
require("after.plugin.theme")
require("after.plugin.telescope")
require("after.plugin.treesitter")
require("after.plugin.cmp")
require("after.plugin.theme")
require("after.plugin.metals")
require("after.plugin.harpoon")
require("after.plugin.gitsigns")
require("after.plugin.lsp")
require("after.plugin.fugitive")
require("after.plugin.mason")
require("after.plugin.netrw")

